version: '3.8'

services:

  node:
    #    build:
    #      context: ./.docker/node
    #      args:
    #        NODE_VERSION: ${NODE_VERSION}
    container_name: ${NAMESPACE}_node
    image: osioaliu/node:${NODE_VERSION}
    working_dir: $WORKDIR_SERVER_NODE
    user: ${UID_GID}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - TZ=${TZ}
    entrypoint: [ "tail", "-f", "/dev/null" ]
    volumes:
      - node_data:${WORKDIR_SERVER_NODE}:delegated

  watchtower:
    container_name: ${NAMESPACE}_watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: ${TZ}
    command: --interval 3600

volumes:
  node_data:
    external: true