version: '3.8'

services:

  node:
    container_name: ${NAMESPACE}_node
    image: osioaliu/node:${NODE_VERSION}
    entrypoint: [ "docker-entrypoint.sh", "tail", "-f", "/dev/null" ]
    environment:
      - NODE_ENV=${NODE_ENV}
      - TZ=${TZ}
    working_dir: $WORKDIR_SERVER_NODE
    user: ${UID_GID}
    ports:
      - "3000:3000"
    volumes:
      - node_data:${WORKDIR_SERVER_NODE}:delegated
#    build:
#      context: ./.docker/node
#      args:
#        NODE_VERSION: ${NODE_VERSION}

#  watchtower:
#    container_name: ${NAMESPACE}_watchtower
#    image: containrrr/watchtower
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    environment:
#      TZ: ${TZ}
#    command: --interval 3600

volumes:
  node_data:
    driver_opts:
      type: none
      o: bind
      device: ${WORKDIR_NODE}
